version: '3.5'

services:
  backend:
    ports:
      - 8213:8213
    build: ./
    networks:
      - backend
    depends_on:
      - postgres
    env_file:
      - database.env

  postgres:
    image: postgres:12
    restart: always
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge

volumes:
  database-data: # named volumes can be managed easier using docker-compose